name: "Repro Spack Buildcache"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  setup-buildcache:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Spack
        uses: spack/setup-spack@v2

      - name: Find Compilers
        run: spack -e . compiler find --mixed-toolchain
        
      - name: Trust Buildcache
        run: spack -e . buildcache keys --install --trust
        
      - name: Concretize
        run: spack -e . -v concretize
        
      - name: Install
        run: |
          spack -e . env depfile -o Makefile
          make -Orecurse -j $(($(nproc) + 1)) SPACK_INSTALL_FLAGS=--no-check-signature
          
      - name: Push packages and update index
        run: |
          spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
          spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --update-index --force local-buildcache
        if: ${{ !cancelled() }}
